services:
  frontend-staging:
    build:
      context: .
      dockerfile: ./Dockerfile.staging
      args:
        NEXT_PUBLIC_API_URL: http://staging-api.baiaotech.org/api/v1
        NEXT_PUBLIC_FORM_LINK: https://forms.gle/ViFkUTk9aFq7LBUg9
        NEXT_PUBLIC_COMMUNITY_API_URL: http://staging-api.baiaotech.org/api/v1/comunidades/
    container_name: frontend-baiaotech-staging
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    # sem command: deixa usar o server.js do standalone
